# _config.yml

title: lxmghct's blog
description: >- # this means to ignore newlines until "baseurl:"
  学习、实践、分享<br>
  Learning, Practicing, Sharing
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
rss_url: /feed.xml

author:
  name: Long, Xiaoming
  address: Tianjin, China
  email: lxmghct@gmail.com
  github: https://github.com/lxmghct
  cnblog: https://www.cnblogs.com/lxm-cnblog
  description: >-
    lxmghct's blog<br>Learning, Practicing, Sharing


# Build settings
theme: minima
plugins:
  - jekyll-feed

port: 4001

sass:
  quiet_deps: true

beaudar:
  repo: lxmghct/blog-comments
  branch: master
  