# _config.yml

title: lxmghct's blog
description: >- # this means to ignore newlines until "baseurl:"
  代码人生：学习、实践、分享<br>
  CodeLife: Learning, Practicing, Sharing
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
rss_url: /feed.xml

author:
  email: lxmghct@gmail.com
  github: https://github.com/lxmghct


# Build settings
theme: minima
plugins:
  - jekyll-feed

port: 4001

sass:
  quiet_deps: true

profile_description: longxiaoming<br>My Journey in Code
  